### PR TITLE
fix: name bid details when expand=true

### LINKED ISSUE #159: missing bid-details for revoked name that is in auction again (expand=true)
we identified following behaviour:
- https://mainnet.aeternity.io/mdw/name/yani.chain?expand=true is **currently** returning an auction and is at the same time a name that was already owned by someone
   - the information about the auction is included in the `auction` object
   - the information about the last ownership is included in the `info` object and `previous` is empty
   - the tx-details of the bids are missing though we are calling with `expand=true` (we only get the tx-index)
        - this is definitely an issue but we might also challenge the place where the bid information is returned (see following "regular" auction)
- https://mainnet.aeternity.io/mdw/name/barclays.chain?expand=true is **currently** returning an auction and was never owned before
   - the information about the auction is included in the `info` object
   - the tx-details of the bids are returned (which is what we want to see for the request above, too)

so we definitely need to have tx-details for the `yani.chain` case and generally it might be a bit confusing to have a separate `auction` object (name with history) whereas for "new names" we get this information in the `info` object

here the current responses:

<details>
  <summary>yani.chain</summary>
  
```json
{
   "active":false,
   "auction":{
      "auction_end":434187,
      "bids":[
         20316528
      ],
      "last_bid":{
         "block_hash":"mh_2XbdMjVr7JMUdHLgeUdMpX48CKuZVbTbGQFLphDeef7mcqHYWQ",
         "block_height":404427,
         "hash":"th_2dX4oYMWuJKGtry4Kw6EKLkZMME7uxaL8352E12FCrskLNkHea",
         "micro_index":4,
         "micro_time":1616615881459,
         "signatures":[
            "sg_FFLU29KdPjSBqKXxXaUpkCwFq3EZTNJvA3WmpajaStc19dAqw4d6tzFHPBygJT4CGNhVFWTG5yvdmQoLsUgvFURWFjsVT"
         ],
         "tx":{
            "account_id":"ak_xdMvnwfmbJ3AN16ZatP1VsiXoaaD3uaAGKKD7KJ8etafGEwrC",
            "fee":16520000000000,
            "name":"yani.chain",
            "name_fee":134626900000000000000,
            "name_id":"nm_xtqsqdz47urb1cFSqJd9ERThzYvsAxWBcH8Hjy1Fdpog3CtXJ",
            "name_salt":6424363597915663,
            "nonce":24,
            "ttl":0,
            "type":"NameClaimTx"
         },
         "tx_index":20316528
      }
   },
   "info":{
      "active_from":191475,
      "auction_timeout":null,
      "claims":[
         {
            "block_hash":"mh_2BWkaePj1n2BremzDiybQQSF4dq7s9n2x6B3XKdtj2uHQww2bU",
            "block_height":161715,
            "hash":"th_KrZkmyt4Rr9ZztxSzAWn8EXh4CZD6USKNDEC2jH3wR8pBhDwH",
            "micro_index":0,
            "micro_time":1572548882360,
            "signatures":[
               "sg_Vh81onLkXvpcjqgCXRoz8FL72ZyMoQPtsufNuuEu2xAq7b8WhgKgkAsxbE97nxqYsVLihiNfGmSBQ2ZByWPyN8iYVECq9"
            ],
            "tx":{
               "account_id":"ak_2ruXgsLy9jMwEqsgyQgEsxw8chYDfv2QyBfCsR6qtpQYkektWB",
               "fee":137500000000000,
               "name":"yani.chain",
               "name_fee":134626900000000000000,
               "name_id":"nm_xtqsqdz47urb1cFSqJd9ERThzYvsAxWBcH8Hjy1Fdpog3CtXJ",
               "name_salt":3729381389837953,
               "nonce":131,
               "type":"NameClaimTx",
               "version":2
            },
            "tx_index":4712022
         }
      ],
      "expire_height":304439,
      "ownership":{
         "current":"ak_2rGuHcjycoZgzhAY3Jexo6e1scj3JRCZu2gkrSxGEMf2SktE3A",
         "original":"ak_2ruXgsLy9jMwEqsgyQgEsxw8chYDfv2QyBfCsR6qtpQYkektWB"
      },
      "pointers":{
         "account_pubkey":"ak_2rGuHcjycoZgzhAY3Jexo6e1scj3JRCZu2gkrSxGEMf2SktE3A"
      },
      "revoke":null,
      "transfers":[
         {
            "block_hash":"mh_25MaM79PAmGmAvpKCsZ1frh3UZ6SCRTbeQ2Q8mjspWYhrWnJq4",
            "block_height":224097,
            "hash":"th_ttpAnDHHBANbJvw6psCv6d6nXbKBtpS5pXVR1PgLRxdwquRz8",
            "micro_index":0,
            "micro_time":1583830472958,
            "signatures":[
               "sg_BeLn8y4oxq2vc5mXoVuf74PqL931iZVe4vhhXqMMkG2qKADdXhwJSzmmTDz25faDzapvchYaRESEGKwwadJJzGRTejAF7"
            ],
            "tx":{
               "account_id":"ak_2ruXgsLy9jMwEqsgyQgEsxw8chYDfv2QyBfCsR6qtpQYkektWB",
               "fee":17320000000000,
               "name":"yani.chain",
               "name_id":"nm_xtqsqdz47urb1cFSqJd9ERThzYvsAxWBcH8Hjy1Fdpog3CtXJ",
               "nonce":228,
               "recipient_id":"ak_2rGuHcjycoZgzhAY3Jexo6e1scj3JRCZu2gkrSxGEMf2SktE3A",
               "type":"NameTransferTx",
               "version":1
            },
            "tx_index":8778145
         }
      ],
      "updates":[
         {
            "block_hash":"mh_qi1dTLGUhVPk6uffv1iEyJxDukGsVdNS1NGQuct6Wev61xVSu",
            "block_height":254439,
            "hash":"th_21d3ziwT2MZMPy9ZsgijjZq5SSowAFL4ahpCa47Do82PPjcwBR",
            "micro_index":38,
            "micro_time":1589326381965,
            "signatures":[
               "sg_JUcZ1cUwbPSyUsPwthYeMv7G9U1vurbcoLm4yZ7o3S6MfG2dS3os9B52n1sagjXzzm1VWG9h5pJJ8u5VXw9QeVci1DUBP"
            ],
            "tx":{
               "account_id":"ak_2rGuHcjycoZgzhAY3Jexo6e1scj3JRCZu2gkrSxGEMf2SktE3A",
               "client_ttl":84600,
               "fee":17780000000000,
               "name":"yani.chain",
               "name_id":"nm_xtqsqdz47urb1cFSqJd9ERThzYvsAxWBcH8Hjy1Fdpog3CtXJ",
               "name_ttl":50000,
               "nonce":75,
               "pointers":[
                  {
                     "id":"ak_2rGuHcjycoZgzhAY3Jexo6e1scj3JRCZu2gkrSxGEMf2SktE3A",
                     "key":"account_pubkey"
                  }
               ],
               "type":"NameUpdateTx",
               "version":1
            },
            "tx_index":11110435
         },
         {
            "block_hash":"mh_2gM6T2E1Cv9D1Zb4yNn7DdaoryNRjHRSJbYb7DKsattMEdrgKk",
            "block_height":248372,
            "hash":"th_2hTS5rMayTcKUoE6dLJiieWKsoQTn8Rvu4ch3uj4hQcjAJiTVd",
            "micro_index":8,
            "micro_time":1588231276425,
            "signatures":[
               "sg_LsGoaEWg1MuN451B3zinD83NiUxTL1VdQbCoofgjcGwxdqzTfQkf9fNWptGvHKqZ2ZYGBHANXgdKB5nidZ6KikUzwd5FA"
            ],
            "tx":{
               "account_id":"ak_2rGuHcjycoZgzhAY3Jexo6e1scj3JRCZu2gkrSxGEMf2SktE3A",
               "client_ttl":84600,
               "fee":17780000000000,
               "name":"yani.chain",
               "name_id":"nm_xtqsqdz47urb1cFSqJd9ERThzYvsAxWBcH8Hjy1Fdpog3CtXJ",
               "name_ttl":50000,
               "nonce":65,
               "pointers":[
                  {
                     "id":"ak_2rGuHcjycoZgzhAY3Jexo6e1scj3JRCZu2gkrSxGEMf2SktE3A",
                     "key":"account_pubkey"
                  }
               ],
               "type":"NameUpdateTx",
               "version":1
            },
            "tx_index":10660028
         },
         {
            "block_hash":"mh_2kD6gu1LKCRiB2jWhuwTtsHBT6RqTuzU2xCB8r9rU2g9ERRDAn",
            "block_height":241000,
            "hash":"th_oEysf8t6CmxWuMCUrtPuACMJFxrGEDPzvtGCAnVYKCguMvDfW",
            "micro_index":62,
            "micro_time":1586893256114,
            "signatures":[
               "sg_QEWPPcpnTYU91fnMR7YCr9ZLKih1REEarnF3r61h3bbrir1RfHeWko9zTNREBbkHNDD293H892Y8x9NESwsbvBDTvWVSj"
            ],
            "tx":{
               "account_id":"ak_2rGuHcjycoZgzhAY3Jexo6e1scj3JRCZu2gkrSxGEMf2SktE3A",
               "client_ttl":84600,
               "fee":17780000000000,
               "name":"yani.chain",
               "name_id":"nm_xtqsqdz47urb1cFSqJd9ERThzYvsAxWBcH8Hjy1Fdpog3CtXJ",
               "name_ttl":50000,
               "nonce":47,
               "pointers":[
                  {
                     "id":"ak_2rGuHcjycoZgzhAY3Jexo6e1scj3JRCZu2gkrSxGEMf2SktE3A",
                     "key":"account_pubkey"
                  }
               ],
               "type":"NameUpdateTx",
               "version":1
            },
            "tx_index":10074155
         }
      ]
   },
   "name":"yani.chain",
   "previous":[
      
   ],
   "status":"auction"
}
```
</details>

<details>
  <summary>barclays.chain</summary>
  
```json
{
   "active":false,
   "info":{
      "auction_end":420173,
      "bids":[
         {
            "block_hash":"mh_2satybPN3jPzW2wEJtQW1ic71ZpdSYeD3rEa2Wk5iD8e5XVRzp",
            "block_height":405293,
            "hash":"th_dR2gnQ2YkDkomdybt758te3C1viVh2RZRGZw1Pq6cdJGTSydo",
            "micro_index":0,
            "micro_time":1616772537827,
            "signatures":[
               "sg_3e31fGwju53wFZdYQfBCe8TJXf1sgR86oeytere2SfN3AfW7s2p2g1YiQi4hHDbyumbv2Bf1ea7uhbXB2U94bZuwKapoG"
            ],
            "tx":{
               "account_id":"ak_5DHWWYtefyLowkDUs9Q3XSWCBP2eEieueMTBwhJZUB4bA4n16",
               "fee":33240000000000,
               "name":"BARCLAYS.chain",
               "name_fee":19641800000000000000,
               "name_id":"nm_uDx9kUfNxvmA75H32JNvuEzy1MwtpDiSouTJXLGsuNiX3hKHE",
               "name_salt":6542793148261715,
               "nonce":149,
               "type":"NameClaimTx",
               "version":2
            },
            "tx_index":20350751
         }
      ],
      "last_bid":{
         "block_hash":"mh_2satybPN3jPzW2wEJtQW1ic71ZpdSYeD3rEa2Wk5iD8e5XVRzp",
         "block_height":405293,
         "hash":"th_dR2gnQ2YkDkomdybt758te3C1viVh2RZRGZw1Pq6cdJGTSydo",
         "micro_index":0,
         "micro_time":1616772537827,
         "signatures":[
            "sg_3e31fGwju53wFZdYQfBCe8TJXf1sgR86oeytere2SfN3AfW7s2p2g1YiQi4hHDbyumbv2Bf1ea7uhbXB2U94bZuwKapoG"
         ],
         "tx":{
            "account_id":"ak_5DHWWYtefyLowkDUs9Q3XSWCBP2eEieueMTBwhJZUB4bA4n16",
            "fee":33240000000000,
            "name":"BARCLAYS.chain",
            "name_fee":19641800000000000000,
            "name_id":"nm_uDx9kUfNxvmA75H32JNvuEzy1MwtpDiSouTJXLGsuNiX3hKHE",
            "name_salt":6542793148261715,
            "nonce":149,
            "type":"NameClaimTx",
            "version":2
         },
         "tx_index":20350751
      }
   },
   "name":"barclays.chain",
   "previous":[
      
   ],
   "status":"auction"
}
```
</details>

### PR DESCRIPTION
**Pull request by jyeshe**
## What

Expands bids tx index list to bids with tx details.

## Why

Fixes #159 

## Validation steps

Specific case:
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/name_controller_test.exs:332`

Regression:
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/name_controller_test.exs`
`elixir --sname aeternity@localhost -S mix test test/ae_mdw_web/controllers/name_controller_test.exs`

## Additional Notes
This PR fixes the bug on expand=true (it happens with not revoked names too). The change on "auction" key to make it more uniform along with "info" will be handled in a separate issue (request).

### CODE REVIEW

File: lib/ae_mdw/auction_bids.ex [hunk 1]
```diff
@@ -72,7 +73,7 @@ defmodule AeMdw.AuctionBids do
   defp render(
          {plain_name, {_block_index, _txi}, expire_height, _owner_pk,
           [{_last_bid_bi, last_bid_txi} | _rest_bids] = bids},
-         _expand?
+         expand?
```
Comment (jyeshe) [inline lib/ae_mdw/auction_bids.ex:76]: not a bug in /names/auctions (not documented so not missing)
