### PR TITLE
Fix runtime error when calling /status endpoint [#123]

### LINKED ISSUE #123: runtime error when calling /status endpoint
I am facing a runtime error when calling `/status` on a virgin node that has no transactions in the database:

```
    ** (RuntimeError) can't get last key for table Elixir.AeMdw.Db.Model.Tx
        (ae_mdw 0.1.0) lib/ae_mdw/db/util.ex:92: AeMdw.Db.Util.ensure_key!/2
        (ae_mdw 0.1.0) lib/ae_mdw_web/controllers/util_controller.ex:57: AeMdwWeb.UtilController.status/2
        (ae_mdw 0.1.0) lib/ae_mdw_web/controllers/util_controller.ex:1: AeMdwWeb.UtilController.action/2
        (ae_mdw 0.1.0) lib/ae_mdw_web/controllers/util_controller.ex:1: AeMdwWeb.UtilController.phoenix_controller_pipeline/2
        (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (ae_mdw 0.1.0) lib/ae_mdw_web/endpoint.ex:1: AeMdwWeb.Endpoint.plug_builder_call/2
        (ae_mdw 0.1.0) lib/plug/debugger.ex:132: AeMdwWeb.Endpoint."call (overridable 3)"/2
        (ae_mdw 0.1.0) lib/ae_mdw_web/endpoint.ex:1: AeMdwWeb.Endpoint.call/2
        (phoenix 1.4.17) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.8.0) /home/aeternity/node/ae_mdw/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /home/aeternity/node/ae_mdw/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /home/aeternity/node/ae_mdw/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### PR DESCRIPTION
**Pull request by wj2016**
Fixed #123

### CODE REVIEW

File: lib/ae_mdw/db/util.ex [hunk 1]
```diff
@@ -256,10 +256,21 @@ defmodule AeMdw.Db.Util do
...
     }
   end
 
+  defp safe_mdw_tx_index_and_height do
+    try do
+      mdw_tx_index = last_txi()
+      {mdw_height, _} = read_tx!(mdw_tx_index) |> Model.tx(:block_index)
+      {mdw_tx_index, mdw_height}
+    rescue
+      e in RuntimeError ->
```
Comment (skkw) [inline lib/ae_mdw/db/util.ex:271]: better use just `_` to catch all, without var name as that would emit unused warning...

**Review by skkw — APPROVED** [review]
