### PR TITLE
fix: get next block hash on async task

### LINKED ISSUE #615: aex9 balance not available
```
error 400 http://localhost:4000/aex9/balances/ct_RDRJC5EySx4TcLtGRWYrXfNgyWzEDzssThJYPd9kdLeS5ECaA
{"error":"balance is not yet available: contract ct_RDRJC5EySx4TcLtGRWYrXfNgyWzEDzssThJYPd9kdLeS5ECaA"}
```

### PR DESCRIPTION
**Pull request by jyeshe**
## What

* Safely gets the hash of next block to compute the aex9 balance during async task processing.
* Initialize aex9 balance with empty mapping to differentiate from `balance is not yet available` condition (`Aex9BalanceNotAvailable` exception)

## Why

Closes #615 

## Validation steps
```
INTEGRATION_TEST=1 elixir --sname aeternity@localhost -S mix test.integration  test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:269

INTEGRATION_TEST=1 elixir --sname aeternity@localhost -S mix test.integration  test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:281
```

## Notes
Other issues involving cached aex9 balance that will be handled in a following PR.

### CODE REVIEW

File: lib/ae_mdw/node/db.ex [hunk 1]
```diff
@@ -16,21 +16,42 @@ defmodule AeMdw.Node.Db do
...
+        {:cont, index + 1}
+      end
+    end)
+    |> case do
+      {:ok, mb_hash} -> mb_hash
+      _mb_count -> next_kb_hash
+    end
+  end
 
+  @spec get_tx_data(binary()) :: tuple()
```
Comment (sborrazas) [inline lib/ae_mdw/node/db.ex:54]: I think we can turn this into
```elixir
(Txs.tx_hash()) :: {Blocks.block_hash(), Node.tx_type(), Node.aext(), Node.tx()}
```

**Review by sborrazas — APPROVED** [review]
Other than the type spec LGTM

**Review by thepiwo — APPROVED** [review]

File: lib/ae_mdw/node/db.ex (hunk 1 above)
Comment (jyeshe) [reply lib/ae_mdw/node/db.ex:54]: This is preexisting, it will be improved in a following PR. Thanks
