### PR TITLE
fix: filtering aex9 call and recipients

### LINKED ISSUE #364: call_not_found error on derive aex9 presence
```
16:51:46.434 [error] Task #PID<0.4487.1> started from AeMdw.Sync.AsyncTasks.LongTaskConsumer terminating
** (RuntimeError) failed on {:error, :call_not_found}
    (ae_mdw 1.2.1) lib/ae_mdw/util.ex:23: AeMdw.Util.ok!/1
    (ae_mdw 1.2.1) lib/ae_mdw/contract.ex:286: AeMdw.Contract.call_tx_info/4
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex:104: anonymous fn/4 in AeMdw.Sync.AsyncTasks.DeriveAex9Presence.read_aex9_transfers_from_mb/3
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex:77: AeMdw.Sync.AsyncTasks.DeriveAex9Presence.get_aex9_recipients/3
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex:44: AeMdw.Sync.AsyncTasks.DeriveAex9Presence.process/1
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/consumer.ex:147: AeMdw.Sync.AsyncTasks.Consumer.process/1
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/consumer.ex:111: anonymous fn/2 in AeMdw.Sync.AsyncTasks.Consumer.run_supervised/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### PR DESCRIPTION
**Pull request by jyeshe**
Fixes #364

### CODE REVIEW

File: lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex [hunk 1]
```diff
@@ -75,7 +75,10 @@ defmodule AeMdw.Sync.AsyncTasks.DeriveAex9Presence do
       [] ->
         contract_pk
         |> read_aex9_transfers_from_mb(kbi, mbi)
-        |> Enum.map(fn [_from_pk, to_pk, <<_amount::256>>] -> to_pk end)
+        |> Enum.flat_map(fn
+          [_from_pk, to_pk, <<_amount::256>>] -> [to_pk]
+          _other -> []
```
Comment (sborrazas) [inline lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex:80]: Why would there be other aex9 transfers format? what are those other formarts?

Comment (jyeshe) [reply lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex:80]: Same logic as here:
https://github.com/aeternity/ae_mdw/blob/78c664828a1445509d09375ad1b9427c3b345e57/lib/ae_mdw/db/sync/contract.ex#L64

There should be none because of this:
https://github.com/aeternity/ae_mdw/blob/78c664828a1445509d09375ad1b9427c3b345e57/lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex#L119

Bottom line this might need improvement but it is how transfers are filtered currently (as contract.ex existing code) outside the scope of the async task.
 
Without it, it gives: https://github.com/aeternity/ae_mdw/issues/364#issuecomment-981884473

**Review by sborrazas — APPROVED** [review]

**Review by thepiwo — APPROVED** [review]
