### PR TITLE
fix: duplicated spend_tx with sender = recipient

### LINKED ISSUE #162: Sending coins to itself makes appear transaction in the list of transactions two times
For example, here: https://mainnet.aeternity.io/mdw/txs/gen/421792-0?account=ak_gvxNbZf5CuxYVfcUFoKAP4geZatWaC2Yy4jpx5vZoCKank4Gc&limit=10&page=1

Transaction th_3rw5nk53rEQzZr8xrQ6sqt2Y9Cv4U8piqiHK1KVkXCaVFMTCq is listed two times.

Obviously, this list shouldn't return duplicate transactions, because the endpoint described as returning transactions related to the account, not incoming/outcoming entries.

### PR DESCRIPTION
**Pull request by jyeshe**
## What

Dedup `/txs?account=:aid` response.

## Why

Indexing by `recipient_id` and `sender_id` is needed to continue to have consistent results when filtering `/txs` by these fields.
Fixes #162 

## Validation steps

Specific:
`elixir --sname aeternity@localhost -S mix test test/ae_mdw/db/sync/transaction_test.exs`
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs:815`

Regression:
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs`

### CODE REVIEW

File: lib/ae_mdw/node.ex [hunk 1]
```diff
@@ -116,6 +116,10 @@ defmodule AeMdw.Node do
   end
 
   @spec tx_ids(atom()) :: %{atom() => non_neg_integer()}
+  def tx_ids(:spend_tx) do
+    %{sender_id: 0, recipient_id: 0}
+  end
+
```
Comment (sborrazas) [inline lib/ae_mdw/node.ex:122]: This is going to be overriden by the `SmartGlobal.new(AeMdw.Node, ...)` call on startup, I'm assuming it's just for documentation purposes?

Comment (jyeshe) [reply lib/ae_mdw/node.ex]: not needed anymore for dialyzer, thanks
