### PR TITLE
fix: add name ttl to last_bid tx

### LINKED ISSUE #354: add ttl to last_bid.tx in names
localhost:
```
{
      "active": false,
      "auction": {
        "auction_end": 530136,
        "bids": [
          27968051
        ],
        "last_bid": {
          "block_hash": "mh_bof6T7dxEuRQoeY9zCmX9CvxSrAinftqQ7cWUtV87Kc7e5wT4",
          "block_height": 515256,
          "hash": "th_2pre6qbBF1aFjnfoe6A5VrfQadPcBeVdY76obzYeQnGwkfxeQT",
          "micro_index": 2,
          "micro_time": 1636820688836,
          "signatures": [
            "sg_677AxnqB8HwwXmUfzrZMUECBtNF7JZMkasw2SEfg2eJtu4n3Zp94TXZ29ZPR2r9MiK5dPCz7ZwteFjNqZwz9boiuMH9r8"
          ],
          "tx": {
            "account_id": "ak_XtJGJrJuvxduT1HFMye4PuEkfUnU9L5rUE5CQ2F9MkqYQVr3f",
            "fee": 16580000000000,
            "name": "Money.chain",
            "name_fee": 83204000000000000000,
            "name_id": "nm_2r4yxFwEpwErriXzC4bQ5Y7krC9SurwHchqfQSFXE4HvZEBEyv",
            "name_salt": 6425855109544945,
            "nonce": 1358,
            "type": "NameClaimTx",
            "version": 2
          },
          "tx_index": 27968051
        }
      },
```
[mainnet:](https://mainnet.aeternity.io/mdw/names/inactive)
```
    {
      "active": false,
      "auction": {
        "auction_end": 530136,
        "bids": [
          27968013
        ],
        "last_bid": {
          "block_hash": "mh_bof6T7dxEuRQoeY9zCmX9CvxSrAinftqQ7cWUtV87Kc7e5wT4",
          "block_height": 515256,
          "hash": "th_2pre6qbBF1aFjnfoe6A5VrfQadPcBeVdY76obzYeQnGwkfxeQT",
          "micro_index": 2,
          "micro_time": 1636820688836,
          "signatures": [
            "sg_677AxnqB8HwwXmUfzrZMUECBtNF7JZMkasw2SEfg2eJtu4n3Zp94TXZ29ZPR2r9MiK5dPCz7ZwteFjNqZwz9boiuMH9r8"
          ],
          "tx": {
            "account_id": "ak_XtJGJrJuvxduT1HFMye4PuEkfUnU9L5rUE5CQ2F9MkqYQVr3f",
            "fee": 16580000000000,
            "name": "Money.chain",
            "name_fee": 83204000000000000000,
            "name_id": "nm_2r4yxFwEpwErriXzC4bQ5Y7krC9SurwHchqfQSFXE4HvZEBEyv",
            "name_salt": 6425855109544945,
            "nonce": 1358,
            "ttl": 0,
            "type": "NameClaimTx"
          },
          "tx_index": 27968013
        }
      },
```

### PR DESCRIPTION
**Pull request by jyeshe**
## What

Adds to auction `last_bid` object the expiration height of a name that is set after its auction (future expiration when the name becomes active).

## Why

Fixes #354   

## Validation steps

`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/name_controller_test.exs`

### CODE REVIEW

File: lib/ae_mdw_web/controllers/transfer_controller.ex [hunk 1]
```diff
@@ -1,4 +1,5 @@
 defmodule AeMdwWeb.TransferController do
+  # credo:disable-for-this-file
```
Comment (sborrazas) [inline lib/ae_mdw_web/controllers/transfer_controller.ex:2]: This isn't needed and only happens because it's branched-off an old master version

File: lib/ae_mdw/db/name.ex [hunk 2]
```diff
@@ -30,6 +31,11 @@ defmodule AeMdw.Db.Name do
     }
   end
 
+  @spec expire_after(pos_integer()) :: pos_integer()
```
Comment (sborrazas) [inline lib/ae_mdw/db/name.ex:34]: Are these two types block heights? If so, we can use AeMdw.Blocks.height(). Otherwise, we should use more descriptive names about what these integers represent

File: lib/ae_mdw_web/controllers/transfer_controller.ex (hunk 1 above)
Comment (jyeshe) [reply lib/ae_mdw_web/controllers/transfer_controller.ex:2]: ci complained, that's why it's disabled (for a file that is not part of PR).

Comment (sborrazas) [reply lib/ae_mdw_web/controllers/transfer_controller.ex:2]: it complained because of the reason I previously mentioned, which is fixed by rebasing with master

Comment (jyeshe) [reply lib/ae_mdw_web/controllers/transfer_controller.ex:2]: done, away of AFK ...

**Review by thepiwo — APPROVED** [review]

**Review by sborrazas — APPROVED** [review]
