### PR TITLE
fix: extract pointers from internal calls

### LINKED ISSUE #477: pointers not found when name is updated with internall call
```
KeyError at GET /name/mydev0123456789.chain
key :pointers not found in: %{abi_version: 3, amount: 0, arguments: [%{type: :address, value: "ak_q6gAYZuB7o7QJhEjQBFsQ2kANY84TkqStppQDF9uADz4rFWTc"}, %{type: :string, value: "mydev0123456789.chain"}], call_data: <<43, 17, 99, 49, 37, 52, 43, 159, 0, 160, 109, 54, 72, 240, 102, 34, 18, 234, 156, 144, 167, 108, 52, 203, 210, 32, 41, 69, 35, 223, 245, 216, 74, 237, 183, 151, 232, 100, 40, 193, 174, 129, 85, 109, 121, 100, ...>>, call_id: <<66, 71, 196, 15, 184, 13, 132, 158, 3, 138, 79, 19, 229, 16, 215, 164, 30, 38, 183, 188, 217, 117, 143, 255, 119, 70, 202, 163, 70, 18, 106, 146>>, call_origin: <<86, 184, 235, 22, 134, 71, 254, 125, 140, 211, 113, 59, 82, 110, 159, 107, 223, 171, 122, 119, 157, 71, 130, 57, 92, 34, 139, 37, 241, 226, 10, 119>>, call_stack: [], caller_id: {:id, :account, <<86, 184, 235, 22, 134, 71, 254, 125, 140, 211, 113, 59, 82, 110, 159, 107, 223, 171, 122, 119, 157, 71, 130, 57, 92, 34, 139, 37, 241, 226, 10, 119>>}, contract_id: {:id, :contract, <<109, 54, 72, 240, 102, 34, 18, 234, 156, 144, 167, 108, 52, 203, 210, 32, 41, 69, 35, 223, 245, 216, 74, 237, 183, 151, 232, 100, 40, 193, 174, 129>>}, fee: 2183280000000000, function: "update_name", gas: 2000000, gas_price: 1000000000, gas_used: 10091, log: [], nonce: 48941, result: :ok, return: %{type: :unit, value: ""}, return_type: :ok, ttl: 443940, type: :contract_call_tx}
```

### PR DESCRIPTION
**Pull request by sborrazas**
closes #477

### CODE REVIEW

File: lib/ae_mdw/db/name.ex [hunk 1]
```diff
@@ -162,16 +163,30 @@ defmodule AeMdw.Db.Name do
...
+      case AE.Db.get_tx_data(tx_hash) do
+        {_block_hash, :name_update_tx, _signed_tx, tx_rec} ->
+          :aens_update_tx.pointers(tx_rec)
+
+        {_block_hash, :contract_call_tx, _signed_tx, _tx_rec} ->
+          txi
+          |> Contracts.fetch_int_contract_calls("AENS.update")
+          |> Enum.reverse()
+          |> Enum.find(fn Model.int_contract_call(tx: tx) ->
+            :aens_update_tx.name_hash(tx) == name_hash
```
Comment (jyeshe) [inline lib/ae_mdw/db/name.ex:182]: don't know if enough, but tx here is a aetx that needs to be specialized.

**Review by jyeshe — CHANGES_REQUESTED** [review]

File: lib/ae_mdw/db/name.ex (hunk 1 above)
Comment (sborrazas) [reply lib/ae_mdw/db/name.ex:184]: I realized that after I saw it, thanks. Also, I added a new type to distinguish tx (the specialized version) and aetx

**Review by thepiwo — APPROVED** [review]

File: lib/ae_mdw/db/name.ex [hunk 2]
```diff
@@ -162,16 +163,34 @@ defmodule AeMdw.Db.Name do
...
-    case Model.name(m_name, :updates) do
-      [{_, txi} | _] ->
-        Format.to_raw_map(read_tx!(txi)).tx.pointers
-        |> Stream.map(&pointer_kv_raw/1)
-        |> Enum.into(%{})
+  def pointers(Model.name(updates: [])), do: %{}
+
+  def pointers(Model.name(index: plain_name, updates: [{_block_index, txi} | _rest_updates])) do
+    Model.tx(id: tx_hash) = read_tx!(txi)
+    name_hash = :aens.get_name_hash(plain_name)
```
Comment (jyeshe) [inline lib/ae_mdw/db/name.ex:170]: not matching because it's a tagged tupple:
```
:aens.get_name_hash("mydev0123456789.chain")
{:ok,
 <<163, 149, 179, 123, 51, 170, 255, 49, 137, 190, 111, 113, 145, 46, 86, 170,
   66, 9, 254, 15, 215, 200, 198, 126, 186, 46, 27, 50, 41, 102, 47, 31>>}
```

File: lib/ae_mdw/db/name.ex [hunk 3]
```diff
@@ -162,16 +163,34 @@ defmodule AeMdw.Db.Name do
...
+
+        {_block_hash, :contract_call_tx, _signed_tx, _tx_rec} ->
+          txi
+          |> Contracts.fetch_int_contract_calls("AENS.update")
+          |> Stream.map(fn Model.int_contract_call(tx: aetx) ->
+            {:name_update_tx, tx} = :aetx.specialize_type(aetx)
+
+            tx
+          end)
+          |> Enum.find(fn tx ->
```
Comment (jyeshe) [inline lib/ae_mdw/db/name.ex:185]: `Enum.find_value` would do the job for the combination of `Enum.map` and `Enum.find`

**Review by jyeshe — CHANGES_REQUESTED** [review]

File: lib/ae_mdw/db/name.ex (hunk 2 above)
Comment (sborrazas) [reply lib/ae_mdw/db/name.ex:170]: Done, thanks
