### PR TITLE
fix: name expiration after aens.update with name_ttl = 0

### LINKED ISSUE #490: aens update expires a name when name_ttl = 0
at 443442
```
iex(aeternity@localhost)1> 08:44:51.100 [error] Supervisor 'Elixir.AeMdw.Db.Sync.Supervisor' had child 'Elixir.AeMdw.Db.Sync' started with 'Elixir.AeMdw.Db.Sync':start_link([]) at <0.1449.0> exit with reason no match of right hand value {aborted,{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"\"mydev0123456789.chain\" not found in Elixir.AeMdw.Db.Model.ActiveName">>},[{'Elixir.AeMdw.Db.Name','cache_through_read!',2,[{file,"lib/ae_mdw/db/name.ex"},{line,280}]},{'Elixir.AeMdw.Db.Sync.Name',transfer,4,[{file,"lib/ae_mdw/db/sync/name.ex"},{line,97}]},{'Elixir.Enum','-each/2-lists^foreach/1-0-',2,[{file,"lib/enum.ex"},{line,783}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,783}]},{mnesia_tm,...},...]}} in 'Elixir.AeMdw.Mnesia':transaction/1 line 160 in context child_terminated
```
This `AENS.update` [internal call](https://mainnet.aeternity.io/mdw/contracts/calls/forward?function=AENS.update&limit=1) with `name_ttl` = 0 is expiring the name while it shouldn't. There is this [NameUpdateTx](https://mainnet.aeternity.io/mdw/txi/28570108 ) that shows that the name should be active.

_Originally posted by @jyeshe in https://github.com/aeternity/ae_mdw/issues/485#issuecomment-1021995978_

### PR DESCRIPTION
**Pull request by jyeshe**
## What

Don't expire a name on update with `name_ttl` = 0 after `AENS.update` internall call.

## Why

Fixes #490 

PS: The contract call with the AENS.update internal call has succeeded. 
https://mainnet.aeternity.io/mdw/txi/23198023

### CODE REVIEW

**Review by thepiwo — APPROVED** [review]

File: lib/ae_mdw/db/sync/name.ex [hunk 1]
```diff
@@ -66,28 +66,31 @@ defmodule AeMdw.Db.Sync.Name do
...
         cache_through_write(Model.ActiveName, m_name)
 
         log_name_change(height, plain_name, "activate")
 
-      delta_ttl == 0 ->
+      delta_ttl == 0 and not internal? ->
         owner = Model.name(m_name, :owner)
         cache_through_delete(Model.ActiveName, plain_name)
         cache_through_delete(Model.ActiveNameOwner, {owner, plain_name})
+        cache_through_delete(Model.ActiveNameExpiration, {old_expire, plain_name})
```
Comment (jyeshe) [inline lib/ae_mdw/db/sync/name.ex:86]: moved here to avoid any expiration operation on the true case (`internal?` or invalid `delta_ttl`)

**Review by sborrazas — APPROVED** [review]
