### PR TITLE
fix: start :aesync and :app_ctrl_server when initializing app

### LINKED ISSUE #275: mdw incompatibility with node 6.3.0
using mdw with node 6.3.0 seems to fail when using the status endpoint

image

### PR DESCRIPTION
**Pull request by sborrazas**
In this new version of aecore (6.3.0) both the :app_ctrl_server process are required for aecore to start syncing and to respond to
functions such as `:asc_sync.sync_progress()`.

This is rather hack-ish, but I don't know why none of these things are started when aecore starts.

closes #275

### CODE REVIEW

**Review by jyeshe — APPROVED** [review]
:raised_hands:

File: priv/migrations/20210914100800_index_inner_txs.ex [hunk 1]
```diff
@@ -28,8 +27,6 @@ defmodule AeMdw.Migrations.IndexInnerTxs do
     if not from_startup? and :ok != Application.ensure_started(:ae_mdw) do
       IO.puts("Ensure sync tables...")
       SyncSup.init_tables()
-      MdwApp.init(:contract_cache)
-      MdwApp.init(:db_state)
```
Comment (jyeshe) [inline priv/migrations/20210914100800_index_inner_txs.ex:32]: Needed by the migration because it replays the sync calling `sync_transaction`.

Comment (jyeshe) [inline priv/migrations/20210914100800_index_inner_txs.ex:32]: Needed by the migration because it replays the sync calling `AeMdw.Db.Sync.Transaction.sync_transaction/4`.

**Review by jyeshe — CHANGES_REQUESTED** [review]
